#!/bin/bash
# Bootstrap: GAME
# Auto-generated by bin/oneshot.sh on 2026-03-22 23:09:34
# Creates target project directory for a new build — run BEFORE opening Claude Code

set -euo pipefail

TARGET_DIR="/mnt/c/Users/barlo/projects/GAME"

if [ -d "$TARGET_DIR/.git" ]; then
    echo "  Existing repo: $TARGET_DIR (branch: $(git -C "$TARGET_DIR" branch --show-current 2>/dev/null || echo none))"
else
    mkdir -p "$TARGET_DIR"
    git -C "$TARGET_DIR" init --quiet
    git -C "$TARGET_DIR" checkout -b main --quiet 2>/dev/null || true
    echo "  Initialized: $TARGET_DIR"
fi

echo ""
echo "Ready. Open Claude Code in the target directory:"
echo "  cd \"/mnt/c/Users/barlo/projects/GAME\" && claude ."
echo "Then paste the oneshot prompt."
